AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  student-api

  Sample SAM Template for student-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  StudentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: students
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  StudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: students/
      Handler: app.app
      Runtime: python3.6
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref StudentTable
      Events:
        Test:
          Type: Api
          Properties:
            Path: /
            Method: get
        ListStudents:
          Type: Api
          Properties:
            Path: /students
            Method: get
        PutStudent:
          Type: Api
          Properties:
            Path: /students
            Method: post
        GetStudent:
          Type: Api
          Properties:
            Path: /students/{id}/
            Method: get
        PatchStudent:
          Type: Api
          Properties:
            Path: /students/{id}/
            Method: patch
        DeleteStudent:
          Type: Api
          Properties:
            Path: /students/{id}/
            Method: delete


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StudentApi:
    Description: "API Gateway endpoint URL for Prod stage for Student function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  StudentFunction:
    Description: "Student Lambda Function ARN"
    Value: !GetAtt StudentFunction.Arn
  StudentFunctionIamRole:
    Description: "Implicit IAM Role created for Student function"
    Value: !GetAtt StudentFunctionRole.Arn
